In [1]:
import numpy as np
import pandas as pd

In [2]:
#Creating data:

Data = {
    'Name' : ['Ali' , 'Ahmad' , 'Bilal' , 'Zain' , 'Shehzad' ],
    'Age'  : [29,25,21,23,20],
    'City' : ['Lahore' , 'Faislabad' , 'Karachi' , 'Islamabad' , 'Lahore' ],
    'Post' : ['HR' , 'Assistent' , 'Employee' , 'Computer Oper' , 'Employee'],
    'Salary': [ 70000 , 60000, 45000, 35000, 48000]
}
table1 = pd.DataFrame(Data)
table1

      Name  Age       City           Post  Salary
0      Ali   29     Lahore             HR   70000
1    Ahmad   25  Faislabad      Assistent   60000
2    Bilal   21    Karachi       Employee   45000
3     Zain   23  Islamabad  Computer Oper   35000
4  Shehzad   20     Lahore       Employee   48000

In [3]:
#By using List:

Data_List = [
    ['Lissa',27,'Islamabad','HR',150000],
    ['Robin',23,'Lhr','Operator',38000],
    ['Roobi',24,'Faislabad','Employee',45000],
    ['Ahad',26,'Islamabad','Employee',49000]
]
table2 = pd.DataFrame(Data_List)
table2

       0   1          2         3       4
0  Lissa  27  Islamabad        HR  150000
1  Robin  23        Lhr  Operator   38000
2  Roobi  24  Faislabad  Employee   45000
3   Ahad  26  Islamabad  Employee   49000

In [4]:
#By using List Adding Columns:

Data_List = [
    ['Lissa',27,'Islamabad','HR',150000],
    ['Robin',23,'Lhr','Operator',38000],
    ['Roobi',24,'Faislabad','Employee',45000],
    ['Ahad',26,'Islamabad','Employee',49000]
]

Column = ['Name','Age','City','Post','Salary']
table3 = pd.DataFrame(Data_List,columns = Column)
table3

    Name  Age       City      Post  Salary
0  Lissa   27  Islamabad        HR  150000
1  Robin   23        Lhr  Operator   38000
2  Roobi   24  Faislabad  Employee   45000
3   Ahad   26  Islamabad  Employee   49000

In [5]:
#SELECTION AND INDEXING IN COLUMNS:

In [6]:
table1

      Name  Age       City           Post  Salary
0      Ali   29     Lahore             HR   70000
1    Ahmad   25  Faislabad      Assistent   60000
2    Bilal   21    Karachi       Employee   45000
3     Zain   23  Islamabad  Computer Oper   35000
4  Shehzad   20     Lahore       Employee   48000

In [7]:
table1['Name']

0        Ali
1      Ahmad
2      Bilal
3       Zain
4    Shehzad
Name: Name, dtype: object

In [8]:
table1[["City","Salary"]]

        City  Salary
0     Lahore   70000
1  Faislabad   60000
2    Karachi   45000
3  Islamabad   35000
4     Lahore   48000

In [9]:
#ADDING COLUMN IN TABLE:

In [10]:
table1

      Name  Age       City           Post  Salary
0      Ali   29     Lahore             HR   70000
1    Ahmad   25  Faislabad      Assistent   60000
2    Bilal   21    Karachi       Employee   45000
3     Zain   23  Islamabad  Computer Oper   35000
4  Shehzad   20     Lahore       Employee   48000

In [11]:
table1["Status"] = ['Married','Unmarried','Unmarried','Married','Unmarried']
table1

      Name  Age       City           Post  Salary     Status
0      Ali   29     Lahore             HR   70000    Married
1    Ahmad   25  Faislabad      Assistent   60000  Unmarried
2    Bilal   21    Karachi       Employee   45000  Unmarried
3     Zain   23  Islamabad  Computer Oper   35000    Married
4  Shehzad   20     Lahore       Employee   48000  Unmarried

In [12]:
#REMOVING COLUMN:

In [13]:
table1

      Name  Age       City           Post  Salary     Status
0      Ali   29     Lahore             HR   70000    Married
1    Ahmad   25  Faislabad      Assistent   60000  Unmarried
2    Bilal   21    Karachi       Employee   45000  Unmarried
3     Zain   23  Islamabad  Computer Oper   35000    Married
4  Shehzad   20     Lahore       Employee   48000  Unmarried

In [14]:
table1.drop("Status",axis = 1,inplace = True)

In [15]:
table1

      Name  Age       City           Post  Salary
0      Ali   29     Lahore             HR   70000
1    Ahmad   25  Faislabad      Assistent   60000
2    Bilal   21    Karachi       Employee   45000
3     Zain   23  Islamabad  Computer Oper   35000
4  Shehzad   20     Lahore       Employee   48000

In [17]:
#SELECTING ROW:

In [18]:
table1

      Name  Age       City           Post  Salary
0      Ali   29     Lahore             HR   70000
1    Ahmad   25  Faislabad      Assistent   60000
2    Bilal   21    Karachi       Employee   45000
3     Zain   23  Islamabad  Computer Oper   35000
4  Shehzad   20     Lahore       Employee   48000

In [19]:
table1.loc[2]

Name         Bilal
Age             21
City       Karachi
Post      Employee
Salary       45000
Name: 2, dtype: object

In [20]:
table1.loc[[2,4]]

      Name  Age     City      Post  Salary
2    Bilal   21  Karachi  Employee   45000
4  Shehzad   20   Lahore  Employee   48000

In [21]:
#SELECTING SUBSET OF ROWS AND COLUMNS:

In [22]:
table1

      Name  Age       City           Post  Salary
0      Ali   29     Lahore             HR   70000
1    Ahmad   25  Faislabad      Assistent   60000
2    Bilal   21    Karachi       Employee   45000
3     Zain   23  Islamabad  Computer Oper   35000
4  Shehzad   20     Lahore       Employee   48000

In [23]:
table1.loc[[2,3]][["Post","Salary"]]

            Post  Salary
2       Employee   45000
3  Computer Oper   35000

In [24]:
table1.loc[[1,2]][["Name","Salary"]]

    Name  Salary
1  Ahmad   60000
2  Bilal   45000

In [25]:
#CONDITIONAL SELECTION:

In [29]:
#Select only person that live in lahore:

table1[table1["City"] == "Lahore"]

      Name  Age    City      Post  Salary
0      Ali   29  Lahore        HR   70000
4  Shehzad   20  Lahore  Employee   48000

In [30]:
#Selecting only Employee:

table1[table1["Post"] == "Employee"]

      Name  Age     City      Post  Salary
2    Bilal   21  Karachi  Employee   45000
4  Shehzad   20   Lahore  Employee   48000

In [38]:
#selecting only those live in lahore and age less than 25:

table1[(table1["Age"] > 25 & table1["City"] == 'Lahore']

TypeError: Cannot perform 'rand_' with a dtyped [object] array and scalar of type [bool]