In [1]:
import numpy as np
import pandas as pd

In [2]:
#LOAD THE DATA:
df = pd.read_csv(r'anime.csv')

In [3]:
df
df.head()

   Rank                                              Title  Score
0     1  Fullmetal Alchemist: BrotherhoodTV (64 eps)Apr...   9.10
1     2  Steins;GateTV (24 eps)Apr 2011 - Sep 20112,473...   9.07
2     3  Bleach: Sennen Kessen-henTV (13 eps)Oct 2022 -...   9.06
3     4  Gintama°TV (51 eps)Apr 2015 - Mar 2016605,113 ...   9.06
4     5  Shingeki no Kyojin Season 3 Part 2TV (10 eps)A...   9.05

In [4]:
df.loc[1]

Rank                                                     2
Title    Steins;GateTV (24 eps)Apr 2011 - Sep 20112,473...
Score                                                 9.07
Name: 1, dtype: object

In [5]:
def extract_episodes(txt):
    check = False
    data = ""
    for i in txt:
        if i == ')':
            check = False
            return data
    
        if check == True:
            data = data + i
        if i == '(':
            check = True

In [6]:
df["Episodes"] = df["Title"].apply(extract_episodes)

In [7]:
df["Episodes"] = df["Episodes"].str.replace("eps","")

In [8]:
 type(df.loc[0]['Episodes'])

str

In [9]:
df["Episodes"] = df['Episodes'].astype(int)

In [10]:
df.head()

   Rank                                              Title  Score  Episodes
0     1  Fullmetal Alchemist: BrotherhoodTV (64 eps)Apr...   9.10        64
1     2  Steins;GateTV (24 eps)Apr 2011 - Sep 20112,473...   9.07        24
2     3  Bleach: Sennen Kessen-henTV (13 eps)Oct 2022 -...   9.06        13
3     4  Gintama°TV (51 eps)Apr 2015 - Mar 2016605,113 ...   9.06        51
4     5  Shingeki no Kyojin Season 3 Part 2TV (10 eps)A...   9.05        10

In [11]:
df.loc[0]['Title']

'Fullmetal Alchemist: BrotherhoodTV (64 eps)Apr 2009 - Jul 20103,218,472 membersManga StoreVolume 1€4.58Preview'

In [12]:
def Extract_time(txt):
    check = False
    data = ""
    for i in range(len(txt)):
        if txt[i]==')':
            for j in range(i+1,i+20):
                data += txt[j]
            return data

In [13]:
df['Time_stamp'] =df['Title'].apply(Extract_time)

In [14]:
df.head()

,Rank,Title,Score,Episodes,Time_stamp
0,1,Fullmetal Alchemist: BrotherhoodTV (64 eps)Apr...,9.10,64,Apr 2009 - Jul 2010
1,2,"Steins;GateTV (24 eps)Apr 2011 - Sep 20112,473...",9.07,24,Apr 2011 - Sep 2011
2,3,Bleach: Sennen Kessen-henTV (13 eps)Oct 2022 -...,9.06,13,Oct 2022 - Dec 2022
3,4,"Gintama°TV (51 eps)Apr 2015 - Mar 2016605,113 ...",9.06,51,Apr 2015 - Mar 2016
4,5,Shingeki no Kyojin Season 3 Part 2TV (10 eps)A...,9.05,10,Apr 2019 - Jul 2019

In [15]:

from datetime import datetime

def calculate_months(date_range):
    start, end = date_range.split(" - ")

    start_date = datetime.strptime(start, "%b %Y")
    end_date = datetime.strptime(end, "%b %Y")

    months = (end_date.year - start_date.year) * 12 + \
             (end_date.month - start_date.month)

    return months

# Apply to the column
df["months"] = df["Time_stamp"].apply(calculate_months)

In [16]:
df.head()

,Rank,Title,Score,Episodes,Time_stamp,months
0,1,Fullmetal Alchemist: BrotherhoodTV (64 eps)Apr...,9.10,64,Apr 2009 - Jul 2010,15
1,2,"Steins;GateTV (24 eps)Apr 2011 - Sep 20112,473...",9.07,24,Apr 2011 - Sep 2011,5
2,3,Bleach: Sennen Kessen-henTV (13 eps)Oct 2022 -...,9.06,13,Oct 2022 - Dec 2022,2
3,4,"Gintama°TV (51 eps)Apr 2015 - Mar 2016605,113 ...",9.06,51,Apr 2015 - Mar 2016,11
4,5,Shingeki no Kyojin Season 3 Part 2TV (10 eps)A...,9.05,10,Apr 2019 - Jul 2019,3

In [17]:
#HIGHEST SCORE IN TABLE:

df[df['Score']== df['Score'].max()]

,Rank,Title,Score,Episodes,Time_stamp,months
0,1,Fullmetal Alchemist: BrotherhoodTV (64 eps)Apr...,9.1,64,Apr 2009 - Jul 2010,15

In [20]:
df['Title'].head()

0    Fullmetal Alchemist: BrotherhoodTV (64 eps)Apr...
1    Steins;GateTV (24 eps)Apr 2011 - Sep 20112,473...
2    Bleach: Sennen Kessen-henTV (13 eps)Oct 2022 -...
3    Gintama°TV (51 eps)Apr 2015 - Mar 2016605,113 ...
4    Shingeki no Kyojin Season 3 Part 2TV (10 eps)A...
Name: Title, dtype: object

In [21]:
df.head()

,Rank,Title,Score,Episodes,Time_stamp,months
0,1,Fullmetal Alchemist: BrotherhoodTV (64 eps)Apr...,9.10,64,Apr 2009 - Jul 2010,15
1,2,"Steins;GateTV (24 eps)Apr 2011 - Sep 20112,473...",9.07,24,Apr 2011 - Sep 2011,5
2,3,Bleach: Sennen Kessen-henTV (13 eps)Oct 2022 -...,9.06,13,Oct 2022 - Dec 2022,2
3,4,"Gintama°TV (51 eps)Apr 2015 - Mar 2016605,113 ...",9.06,51,Apr 2015 - Mar 2016,11
4,5,Shingeki no Kyojin Season 3 Part 2TV (10 eps)A...,9.05,10,Apr 2019 - Jul 2019,3

In [22]:
#Highest episodes count:

df[df['Episodes'] == df['Episodes'].max()]

,Rank,Title,Score,Episodes,Time_stamp,months
15,16,"GintamaTV (201 eps)Apr 2006 - Mar 20101,034,41...",8.94,201,Apr 2006 - Mar 2010,47

In [24]:
df['Episodes'].head()

0    64
1    24
2    13
3    51
4    10
Name: Episodes, dtype: int64