In [1]:
import numpy as np
import pandas as pd

In [2]:
Data_Employee = pd.DataFrame ({
    'Employee_Id' : [1,2,3,4,5,6],
    'Employee_Name' : ['Ali','Ahmad','Zain','Kashif','Hassan','Sahil'],
    'Department' : [ 'HR ','Employee','Employee','HR','IT','Finance']
})

Salaries = pd.DataFrame ({
    'Employee_Id': [1,2,3,4,7,8],
    'Salary' : [50000,35000,38000,55000,40000,37000],
     'Bonus' : [20000,10000,12000,23000,17000,15000]
        })

In [3]:
Data_Employee

   Employee_Id Employee_Name Department
0            1           Ali        HR
1            2         Ahmad   Employee
2            3          Zain   Employee
3            4        Kashif         HR
4            5        Hassan         IT
5            6         Sahil    Finance

In [4]:
Salaries

   Employee_Id  Salary  Bonus
0            1   50000  20000
1            2   35000  10000
2            3   38000  12000
3            4   55000  23000
4            7   40000  17000
5            8   37000  15000

In [5]:
pd.merge(Data_Employee,Salaries)

   Employee_Id Employee_Name Department  Salary  Bonus
0            1           Ali        HR    50000  20000
1            2         Ahmad   Employee   35000  10000
2            3          Zain   Employee   38000  12000
3            4        Kashif         HR   55000  23000

In [6]:
pd.merge(Data_Employee,Salaries,how ='outer')

   Employee_Id Employee_Name Department   Salary    Bonus
0            1           Ali        HR   50000.0  20000.0
1            2         Ahmad   Employee  35000.0  10000.0
2            3          Zain   Employee  38000.0  12000.0
3            4        Kashif         HR  55000.0  23000.0
4            5        Hassan         IT      NaN      NaN
5            6         Sahil    Finance      NaN      NaN
6            7           NaN        NaN  40000.0  17000.0
7            8           NaN        NaN  37000.0  15000.0

In [7]:
pd.merge(Data_Employee,Salaries,how ='inner')

   Employee_Id Employee_Name Department  Salary  Bonus
0            1           Ali        HR    50000  20000
1            2         Ahmad   Employee   35000  10000
2            3          Zain   Employee   38000  12000
3            4        Kashif         HR   55000  23000

In [8]:
pd.merge(Data_Employee,Salaries,how ='right')

   Employee_Id Employee_Name Department  Salary  Bonus
0            1           Ali        HR    50000  20000
1            2         Ahmad   Employee   35000  10000
2            3          Zain   Employee   38000  12000
3            4        Kashif         HR   55000  23000
4            7           NaN        NaN   40000  17000
5            8           NaN        NaN   37000  15000

In [9]:
pd.merge(Data_Employee,Salaries,how ='left')

   Employee_Id Employee_Name Department   Salary    Bonus
0            1           Ali        HR   50000.0  20000.0
1            2         Ahmad   Employee  35000.0  10000.0
2            3          Zain   Employee  38000.0  12000.0
3            4        Kashif         HR  55000.0  23000.0
4            5        Hassan         IT      NaN      NaN
5            6         Sahil    Finance      NaN      NaN

In [11]:
##Concating :

In [14]:
df1 = pd.DataFrame ({
    'A' : ['A0','A1','A2'],
    'B ': ['B0','B1','B2'],
    'C' : ['C0','C1','C2']
})
df2 =pd.DataFrame ({
    'A' : ['A3','A4','A5'],
    'B' : ['B3','B4','B5'],
    'C' : ['C3','C4','C5']
})

In [19]:
df1

    A  B    C
0  A0  B0  C0
1  A1  B1  C1
2  A2  B2  C2

In [20]:
df2

    A   B   C
0  A3  B3  C3
1  A4  B4  C4
2  A5  B5  C5

In [21]:
pd.concat([df1,df2])

    A   B    C    B
0  A0   B0  C0  NaN
1  A1   B1  C1  NaN
2  A2   B2  C2  NaN
0  A3  NaN  C3   B3
1  A4  NaN  C4   B4
2  A5  NaN  C5   B5

In [18]:
pd.concat([df1,df2],axis = 1)

    A  B    C   A   B   C
0  A0  B0  C0  A3  B3  C3
1  A1  B1  C1  A4  B4  C4
2  A2  B2  C2  A5  B5  C5

In [22]:
##JOINING :

In [25]:
df1 = pd.DataFrame ({
    'Name' : ['Alice','Alizy','Herry']},
    index =  [1,2,3]
)
df2 = pd.DataFrame ({
    'Score' :[86,93,67]},
    index = [2,3,4]
)

In [26]:
df1

    Name
1  Alice
2  Alizy
3  Herry

In [27]:
df2

   Score
2     86
3     93
4     67

In [28]:
df1.join(df2)

    Name  Score
1  Alice    NaN
2  Alizy   86.0
3  Herry   93.0

In [36]:
dd = df1.join(df2,how = 'outer')
dd

    Name  Score
1  Alice    NaN
2  Alizy   86.0
3  Herry   93.0
4    NaN   67.0

InvalidIndexError: (slice(1, 4, None),)