In [1]:
import numpy as np
import pandas as pd

In [2]:
#FINDING MISSING DATA:

In [6]:
data = {
   'A' : [1,np.nan,8,5,7],
   'B' : [np.nan,6,2,1,1],
   'C' : [1,2,3,np.nan,np.nan],
   'D' : [8,9,np.nan,5,1]
}
df=pd.DataFrame(data)

In [7]:
df

     A    B    C    D
0  1.0  NaN  1.0  8.0
1  NaN  6.0  2.0  9.0
2  8.0  2.0  3.0  NaN
3  5.0  1.0  NaN  5.0
4  7.0  1.0  NaN  1.0

In [8]:
df.isna()

       A      B      C      D
0  False   True  False  False
1   True  False  False  False
2  False  False  False   True
3  False  False   True  False
4  False  False   True  False

In [9]:
df.isna().sum()

A    1
B    1
C    2
D    1
dtype: int64

In [12]:
df.isna().any()

A    True
B    True
C    True
D    True
dtype: bool

In [13]:
#REMOVING MISSING DATA:

In [14]:
df

     A    B    C    D
0  1.0  NaN  1.0  8.0
1  NaN  6.0  2.0  9.0
2  8.0  2.0  3.0  NaN
3  5.0  1.0  NaN  5.0
4  7.0  1.0  NaN  1.0

In [15]:
df.dropna()

Empty DataFrame
Columns: [A, B, C, D]
Index: []

In [21]:
df.dropna(thresh =3)

     A    B    C    D
0  1.0  NaN  1.0  8.0
1  NaN  6.0  2.0  9.0
2  8.0  2.0  3.0  NaN
3  5.0  1.0  NaN  5.0
4  7.0  1.0  NaN  1.0

In [22]:
#FILLING THE MISSING DATA:

In [23]:
df

     A    B    C    D
0  1.0  NaN  1.0  8.0
1  NaN  6.0  2.0  9.0
2  8.0  2.0  3.0  NaN
3  5.0  1.0  NaN  5.0
4  7.0  1.0  NaN  1.0

In [24]:
df.fillna(0)

     A    B    C    D
0  1.0  0.0  1.0  8.0
1  0.0  6.0  2.0  9.0
2  8.0  2.0  3.0  0.0
3  5.0  1.0  0.0  5.0
4  7.0  1.0  0.0  1.0

In [25]:
df.fillna('A' : 20 ,'B' :580 ,'C' : 56 ,'D' : 29)

SyntaxError: invalid syntax (1985683270.py, line 1)